#!/usr/bin/env python3.10
r"""
Usage:
    cipher encode <password>
    cipher decode <password>
    cipher -h | --help

Commands:
    encode         Encode message from stdin using specified password.
    decode         Use specified password in order to decode the code.

Options:
    -h --help      Show this screen.
"""
import hashlib
import sys


def hash(msg: bytes):
    return hashlib.sha3_512(msg).digest()


def xor(x: bytes, y: bytes):
    return bytes(x ^ y for x, y in zip(x, y))


def do_the_thing(password: str, message: bytes, action: str):
    assert action in ("encrypt", "decrypt")
    seed, result = int.from_bytes(hash(password.encode()), "little"), []
    if action == "encrypt":
        message = bytes([len(message) % 256]) + message
    for i in range(0, len(message), 64):
        secret = hash((seed + i).to_bytes(128, "little"))
        result.append(xor(message, secret))
    result = b"".join(result)
    return result[1:] if action == "decrypt" else result


if __name__ == "__main__":
    args = __import__("docopt").docopt(__doc__)
    argument = sys.stdin.buffer.read()
    action = "encrypt" if args["encode"] else "decrypt"
    result = do_the_thing(args["<password>"], argument, action)
    sys.stdout.buffer.write(result)
