#!/usr/bin/env python3
from pathlib import Path
import sys


def main(args: list[str]) -> None:
    input_path: Path | None = None
    output_path: Path | None = None
    paths: list[Path] = []
    args_iter = iter(args[1:])
    for arg in args_iter:
        if arg in ("-o", "--output"):
            output_path = Path(next(args_iter))
        elif arg in ("-i", "--input"):
            input_path = Path(next(args_iter))
        else:
            paths.append(Path(arg))
    if input_path is not None:
        unpack_unification(
            input_path.read_text(encoding="utf-8").splitlines(),
            root=input_path.parent.resolve(),
        )
        input_path.unlink()
    output = "".join(
        line + "\n"
        for line in pack_unification(paths, output_path.parent.resolve() if output_path else None)
    )
    if output_path is None:
        print(output.strip())
        return
    output_path.write_text(output, encoding="utf-8", newline="\n")


def pack_unification(paths: list[Path], root: Path | None) -> list[str]:
    unified_source = [
        "# " + str(path.resolve().relative_to(root) if root else path) for path in paths
    ]
    unified_source.append("")
    texts = [path.read_text(encoding="utf-8").splitlines() for path in paths]
    prefix_length = len(paths) + sum(len(str(len(txt))) for txt in texts) - 1
    hists = [get_strings(txt) for txt in texts]
    for line in get_common(*hists):
        prefix = ":".join(",".join(map(str, h[line])) for h in hists)
        prefix = "#" + prefix.ljust(prefix_length) + "#"
        prefix = "#" + hashstr(line)
        unified_source.append(prefix.ljust(8) + line)
    return unified_source


def unpack_unification(lines: list[str], root: Path) -> None:
    paths: list[Path] = []
    lines_iter = iter(lines)
    for line in lines_iter:
        if not line.strip():
            break
        paths.append(root / Path(line[2:]))
    hashes: dict[str, str] = {}
    last_hash = ""
    for line in lines_iter:
        if not line:
            continue
        if line.startswith("#"):
            last_hash = line[1:8].strip()
            hashes[last_hash] = line[8:]
        elif last_hash:
            hashes[last_hash] += "\n" + line[8:]
    texts = [path.read_text(encoding="utf-8").splitlines() for path in paths]
    hists = [get_strings(txt) for txt in texts]
    for line in get_common(*hists):
        updated_line = hashes[hashstr(line)]
        for lines, hist in zip(texts, hists):
            for i in hist[line]:
                lines[i] = updated_line
    for path, lines in zip(paths, texts):
        path.write_text("".join(line + "\n" for line in lines), encoding="utf-8", newline="\n")


HASHES: dict[str, str] = {}


def hashstr(line: str) -> str:
    x = 0
    for ch in line:
        x = (ord(ch) + 255 * x) & 0xFFFF
    hsh = f"{x:04X}"
    if hsh in HASHES and HASHES[hsh] != line:
        sibling = HASHES[hsh]
        raise ValueError(f"Hash collision:\n\t{line!r}\n\t{sibling!r}")
    HASHES[hsh] = line
    return hsh


def get_strings(lines: list[str]) -> dict[str, list[int]]:
    histogram: dict[str, list[int]] = {}
    for i, line in enumerate(lines):
        if line.strip():
            hashstr(line)
            histogram.setdefault(line, []).append(i)
    return histogram


def get_common(*histograms: dict[str, list[int]]) -> list[str]:
    lines: list[str] = []
    for line in histograms[0]:
        if all(line in histograms[i] for i in range(1, len(histograms))):
            lines.append(line)
    # lines.sort()
    return lines


if __name__ == "__main__":
    main(sys.argv)
