#!/usr/bin/env python3
"""
Draw a tree.

Usage: {script} [options] [ABOBA]

Arguments:
    ABOBA - Aboba.

Options:
    -h, --help
        Show this screen and exit.
"""
from itertools import islice
import sys
from contextlib import suppress
from pathlib import Path
import random
import os


def draw_tree(image, x: int, y: int):
    tree = [(x, y)]
    for _ in range(random.randint(3, 8)):
        y += 1
        tree.append((x, y))
    w = random.randint(3, 5)
    x -= random.randint(0, w)
    tree.extend([(x, y) for x in range(x, x + w)])
    branches = [(x, y), (x + w, y)]
    counter = 0
    sign = 1
    while branches:
        counter += 1
        new_branches = []
        for x, y in branches:
            tree.append((x, y))
            if random.choice(range(30 - counter)) == 0:
                continue
            if sign == 5:
                sign = random.choice((-1, +1))
                for _ in range(random.randint(0, 2)):
                    x += sign
                    tree.append((x, y))
            else:
                if random.randint(0, 10) == 0 and len(branches) < 4:
                    tree.append((x - 1, y))
                    tree.append((x + 1, y))
                    new_branches.extend([(x - 1, y), (x + 1, y)])
                sign = abs(sign) + 1
            new_branches.append((x, y + 1))
        branches = list(set(new_branches))
    for x, y in sorted(tree):
        if not image[y - 1][x - 1]:
            image[y][x] = [128, 0, 128]
        elif random.randint(0, 1) == 1:
            image[y - 1][x - 1] = None
            image[y][x] = [128, 0, 128]


def main(script_name: str, *script_args: str):
    doc = __doc__.format(script=Path(script_name).name)
    args = __import__("docopt").docopt(doc, script_args)
    _ = args
    w, h = os.get_terminal_size()
    image = [[None] * w for _ in range(h * 2)]
    trees = w // 20
    tree_w = w // trees
    for x in range((w - trees * tree_w) // 2 + tree_w // 2, w, tree_w):
        draw_tree(image, x, 2)
    print_rgb8_image(image)


def print_rgb8_image(image: list[list[list[int] | None]]):
    if len(image) % 2 == 1:
        image = image + [[None] * len(image[0])]
    lines = []
    for line1, line2 in chunked(image, 2):
        line = []
        for rgb1, rgb2 in zip(line1, line2):
            if rgb1:
                code1 = ";".join(map(str, rgb1))
                code2 = ("48;2;" + ";".join(map(str, rgb2))) if rgb2 else "49"
                line.append(f"\x1b[38;2;{code1};{code2}m▄")
            elif rgb2:
                code = ";".join(map(str, rgb2))
                line.append(f"\x1b[38;2;{code};49m▀")
            else:
                line.append("\x1b[49m ")
        lines.append("".join(line) + "\x1b[0m")
    print("\n".join(reversed(lines)))


def chunked(iterable, n: int):
    it = iter(iterable)
    while chunk := list(islice(it, n)):
        yield chunk


if __name__ == "__main__":
    with suppress(KeyboardInterrupt):
        main(sys.argv[0], *sys.argv[1:])
