#!/usr/bin/env python3

from pathlib import Path
from shutil import rmtree

path = str(Path().resolve()) + "/"
while True:
    for length in reversed(range(1, 1 + 8)):
        try:
            new_path = path + "DELETEME"[:length] + "/"
            Path(new_path).mkdir(exist_ok=True)
            path = new_path
            break
        except OSError:
            pass
    else:
        break
max_path_length = len(path)
print("max path length:", max_path_length)

root = str(Path().resolve()) + "/DELETEME/"
depth = 1
try:
    path = root
    while True:
        new_path = path + "X/"
        Path(new_path).mkdir(exist_ok=True)
        path = new_path
        depth += 1
except OSError:
    rmtree(Path(root), ignore_errors=True)

print("max path depth:", depth)
