#!/usr/bin/env python3.10
r"""
Usage:
    random-arithmetic-expression [EXPR_LENGTH]
    random-arithmetic-expression -h | --help

Arguments:
    expr_length        Length of generated formula

Options:
    -h --help      Show this screen.
"""
from random import randint, choice


def random_expr(length: int):
    if length < 5:
        number = randint(10 ** (length - 1) - (length == 1), 10**length - 1)
        return str(number)
    i = randint(1, length - 4)
    x, y = random_expr(i), random_expr(length - 3 - i)
    return x + " " + choice("+-*/") + " " + y


def main(**args):
    try:
        length = int(args["EXPR_LENGTH"])
    except Exception:
        length = 72
    for _ in range(max(1, length // 2)):
        print(random_expr(length))


if __name__ == "__main__":
    main(**__import__("docopt").docopt(__doc__))
