#!/usr/bin/env python3
"""
Just simple walker in non-euclidian spaces.

Usage: {script} [options] SPACE

Arguments:
    SPACE - The space to walk in.
            Available spaces:
            Euclidian

Options:
    -h, --help
        Show this screen and exit.
"""
import math
import struct
import time
import threading
import select
import queue
import os
import contextlib
from itertools import islice
from time import sleep
import sys
from contextlib import suppress
from pathlib import Path

PALETTE = "000 fff"


def main(script_name: str, *script_args: str):
    doc = __doc__.format(script=Path(script_name).name)
    args = __import__("docopt").docopt(doc, script_args)
    space = args["SPACE"]
    assert space.lower() in ["euclidian"]
    d = euclidian_distance
    x, y = 0.0, 0.0
    dots = []
    with KeyReader() as key_reader:
        render((x, y), dots, distance=d)
        running = True
        while running:
            key = key_reader.get_key()
            if key == "up":
                x += zero(lambda dx: d(x, y, x + dx, y) - 1)
            elif key == "down":
                x -= zero(lambda dx: d(x, y, x - dx, y) - 1)
            elif key == "right":
                y += zero(lambda dy: d(x, y, x, y + dy) - 1)
            elif key == "left":
                y -= zero(lambda dy: d(x, y, x, y - dy) - 1)
            render((x, y), dots, distance=d)


def render(player, points, distance):
    w, h = os.get_terminal_size()
    h = (h - 1) * 2
    palette = [str_to_color(color) for color in PALETTE.split()]
    buffer = [[palette[0] for _ in range(w)] for _ in range(h)]
    x0, y0 = player
    for x, y, color in points:
        dx = distance(x0, y0, x, y0)
        dy = distance(x, y0, x, y)
        i = round(w // 2 + dx)
        j = round(h // 2 - dy)
        if 0 <= i < w and 0 <= j < h:
            buffer[j][i] = palette[color]
    print(x0, y0)
    print_rgb8_image(buffer)
    print(x0, y0)


def euclidian_distance(x0, y0, x1, y1):
    return (x0 - x1) ** 2 + (y0 - y1) ** 2


def zero(f):
    x1 = 0
    x2 = 2**31 - 2**23
    while x2 > x1:
        x = (x1 + x2) // 2
        y = f(float_from_integer(x))
        if y > 0:
            x2 = x - 1
        elif y < 0:
            x1 = x + 1
        else:
            return float_from_integer(x)
    return float_from_integer(x1)


def float_from_integer(integer):
    return struct.unpack("!f", struct.pack("!I", integer))[0]


def print_rgb8_image(image: list[list[list[int] | None]]):
    if len(image) % 2 == 1:
        image = image + [[None] * len(image[0])]
    lines = []
    for line1, line2 in chunked(image, 2):
        line = []
        for rgb1, rgb2 in zip(line1, line2):
            if rgb1:
                code1 = ";".join(map(str, rgb1))
                code2 = ("48;2;" + ";".join(map(str, rgb2))) if rgb2 else "49"
                line.append(f"\x1b[38;2;{code1};{code2}m▄")
            elif rgb2:
                code = ";".join(map(str, rgb2))
                line.append(f"\x1b[38;2;{code};49m▀")
            else:
                line.append("\x1b[49m ")
        lines.append("".join(line) + "\x1b[0m")
    for line in reversed(lines):
        try:
            print(line, flush=True)
        except BlockingIOError:
            pass


def chunked(iterable, n: int):
    it = iter(iterable)
    while chunk := list(islice(it, n)):
        yield chunk


def str_to_color(color: str) -> list[int]:
    if len(color) == 3:
        return [int(c, 16) * 16 + int(c, 16) for c in color]
    return [int(color[i: i + 2], 16) for i in range(0, 6, 2)]


class KeyReader:
    def __init__(self):
        self.unix_mode = os.name != "nt"
        self.pressed_keys = queue.Queue()
        self._thread = None
        self._cmnctr = None
        if self.unix_mode:
            self.get_key = self.pressed_keys.get

    @property
    def running(self):
        return self._thread is not None

    def start(self):
        assert not self.running, "Can't start running key reader"
        assert sys.stdin.isatty(), "Stdin does not look like TTY..."
        self._cmnctr = os.pipe2(os.O_NONBLOCK) if self.unix_mode else [[False]]
        thread_target = unix_read_keys if self.unix_mode else win_read_keys
        self._thread = threading.Thread(target=thread_target, args=[self._cmnctr[0], self.pressed_keys])
        self._thread.start()

    def get_key(self, block=True, timeout=None):
        if not block:
            return self.pressed_keys.get(False)
        deadline = time.monotonic() + (timeout or float("inf"))
        while (timeout := deadline - time.monotonic()) > 0.002:
            with contextlib.suppress(queue.Empty):
                return self.pressed_keys.get(timeout=0.001)
        return self.pressed_keys.get(timeout=timeout)

    def stop(self):
        assert self.running, "Can't stop stopped key reader"
        if self.unix_mode:
            os.write(self._cmnctr[1], b"\x00")
            self._thread.join()
            list(map(os.close, self._cmnctr))
        else:
            self._cmnctr[0][0] = True
            self._thread.join()
        self._thread = None

    def __enter__(self) -> "KeyReader":
        self.start()
        return self

    def __exit__(self, *_):
        self.stop()

    def __del__(self):
        assert not self.running, "You forgot to stop the key reader"


INPUT_SEQUENCES = {
    "\x1b": "escape",
    "\x7f": "backspace",
    "\x08": "backspace",
    "\r": "\n",
    "[3~": "delete",
    "[2~": "insert",
    "[A": "up",
    "[D": "left",
    "[B": "down",
    "[C": "right",
    "[E": "five",
    "[G": "five",
    "[H": "home",
    "[1~": "home",
    "[F": "end",
    "[4~": "end",
    "[5~": "pageup",
    "[6~": "pagedown",
    "OP": "f1",
    "[[A": "f1",
    "OQ": "f2",
    "[[B": "f2",
    "OR": "f3",
    "[[C": "f3",
    "OS": "f4",
    "[[D": "f4",
    "[15~": "f5",
    "[[E": "f5",
    "[17~": "f6",
    "[18~": "f7",
    "[19~": "f8",
    "[20~": "f9",
    "[21~": "f10",
    "[23~": "f11",
    "[24~": "f12",
}
WINDOWS_INPUT_SEQUENCES = {
    "S": "delete",
    "R": "insert",
    "H": "up",
    "K": "left",
    "P": "down",
    "M": "right",
    "G": "home",
    "O": "end",
    "I": "pg_up",
    "Q": "pg_down",
    ";": "f1",
    "<": "f2",
    "=": "f3",
    ">": "f4",
    "?": "f5",
    "@": "f6",
    "A": "f7",
    "B": "f8",
    "C": "f9",
    "D": "f10",
    "\x85": "f11",
    "\x86": "f12",
}


def parse_input_sequences(chars: str):
    i = 0
    while i < len(chars):
        char = chars[i]
        if char != "\x1b" or i + 1 == len(chars):
            yield INPUT_SEQUENCES.get(char, char)
            i += 1
            continue
        for j in range(i + 5, i + 2, -1):
            if chars[i + 1: j] in INPUT_SEQUENCES:
                yield INPUT_SEQUENCES[chars[i + 1: j]]
                i = j
                break
        else:
            yield "alt+" + chars[i + 1]
            i += 2


def unix_read_keys(communication_fd: int, key_buffer: queue.Queue):
    import fcntl
    import termios

    stdin_fd = sys.stdin.fileno()
    tty_flags = termios.tcgetattr(stdin_fd)
    fcntl_flags = fcntl.fcntl(stdin_fd, fcntl.F_GETFL)
    (cur_tty_flags := tty_flags.copy())[3] &= ~termios.ICANON & ~termios.ECHO
    termios.tcsetattr(stdin_fd, termios.TCSANOW, cur_tty_flags)
    fcntl.fcntl(stdin_fd, fcntl.F_SETFL, fcntl_flags | os.O_NONBLOCK)
    rlist = [sys.stdin, communication_fd]
    while select.select(rlist, [], [])[0] == [sys.stdin]:
        for key in parse_input_sequences(sys.stdin.read()):
            key_buffer.put(key)
    termios.tcsetattr(stdin_fd, termios.TCSADRAIN, tty_flags)
    fcntl.fcntl(stdin_fd, fcntl.F_SETFL, fcntl_flags)


def win_read_keys(is_interrupted: list[bool], key_buffer: queue.Queue):
    import msvcrt

    while not is_interrupted[0]:
        if msvcrt.kbhit():
            char = msvcrt.getwch()
            if char in "\x00\xe0":
                char = msvcrt.getwch()
                char = WINDOWS_INPUT_SEQUENCES.get(char, char)
            else:
                char = INPUT_SEQUENCES.get(char, char)
            key_buffer.put(char)
        else:
            time.sleep(0.001)


if __name__ == "__main__":
    with suppress(KeyboardInterrupt):
        main(sys.argv[0], *sys.argv[1:])
